FROM tck-xinan-registry.cn-chengdu.cr.aliyuncs.com/wair/univla:base

# install packages
RUN apt-get update && apt-get -y upgrade && \
    pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple  && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /workspace/univla
COPY ./experiments /workspace/univla/experiments
COPY ./InternVL /workspace/univla/InternVL
COPY ./latent_action_model /workspace/univla/latent_action_model
COPY ./prismatic /workspace/univla/prismatic
COPY ./scripts /workspace/univla/scripts
COPY ./hubconf.py /workspace/univla/hubconf.py
COPY ./requirements.txt /workspace/univla/requirements.txt

CMD ["bash"]